/* Copyright (c) 2006-2007 by Princeton University
 * All rights reserved.
 * Author: Christian Bienia
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Princeton University nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY PRINCETON UNIVERSITY ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL PRINCETON UNIVERSITY BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/** \file config.h
 * \brief The configuration file for PARSEC Hooks Instrumentation API.
 *
 * This file serves as a central point to enable or disable functionality of
 * the hooks library functions. To enable functionality simply define the
 * corresponding macro to be 1 and 0 otherwise.
 *
 * The Hooks API is specified in file hooks.h and the functionality is
 * implemented in file hooks.c.
 */

#ifndef _PARSEC_HOOKS_CONFIG_H
/** Guard macro to prevent multiple inclusions. */
#define _PARSEC_HOOKS_CONFIG_H 1

/*** Configuration ***/

/** \brief Measure execution time of Region-of-Interest.
 *
 * If this macro is defined to 1 code is added to the hook functions to
 * measure the execution time of the Region-of-Interest. Measuring execution
 * time of the whole program is inaccurate because it includes the
 * initialization and shutdown phase.
 *
 * This functionality is enabled by default.
 */
#define ENABLE_TIMING 1

/** \brief Prefix for all output.
 *
 * This macro defines the prefix to use for all output generated by the hooks
 * library. A descriptive prefix makes it easier to distinguish hooks library
 * output from program output at runtime.
 *
 * By default the string "[HOOKS]" is used.
 */
#define HOOKS_PREFIX "[HOOKS]"

#define ENABLE_GEM5_HOOKS 0

#if ENABLE_GEM5_HOOKS
/** \brief Prefix for gem5 hooks.
 *
 * By default the string "[GEM5]" is used.
 */
#define GEM5_HOOKS_PREFIX "[GEM5]"
#endif

/** \brief Version number of this implementation of the PARSEC hooks
 *
 * This macro defines a version string which is part of the output that is
 * printed by the hooks library at the beginning of program execution if the
 * PARSEC workload was compiled with hook support enabled. A unique version
 * string makes it easier to distinguish which version of the hooks library the
 * program has been linked to.
 */
#define HOOKS_VERSION "1.2"

#endif //_PARSEC_HOOKS_CONFIG_H
